CREATE TABLE lgbtq_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL,
    full_name TEXT NOT NULL,
    password TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    bio TEXT,
    profile_pic TEXT NOT NULL,
    interests TEXT NOT NULL,
    pronouns TEXT
);