CREATE TABLE lgbtq_conversations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sender_id INTEGER REFERENCES lgbtq_users(id),
    
    date_created TIMESTAMP DEFAULT now() NOT NULL,
);