CREATE TABLE lgbtq_messages (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    conversation_id INTEGER REFERENCES lgbtq_conversations(id),
    user_id INTEGER REFERENCES lgbtq_users(id),
    content TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
);